// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQeNClAszaLHxvRu4KKemhIoZaF3i-n0',
    appId: '1:924544352485:web:753d6b3437ee6ee6fc940c',
    messagingSenderId: '924544352485',
    projectId: 'h3devsss',
    authDomain: 'h3devsss.firebaseapp.com',
    storageBucket: 'h3devsss.appspot.com',
    measurementId: 'G-Q0GRB7QL35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHdAnHkDfqPggfw9AdUxeJBRmw1gI1AJ4',
    appId: '1:924544352485:android:29907cf360b7869ffc940c',
    messagingSenderId: '924544352485',
    projectId: 'h3devsss',
    storageBucket: 'h3devsss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHa-uzc3YWf7ICAXqBg5DWB_Zs8-euStM',
    appId: '1:924544352485:ios:73a0e059d6385ecefc940c',
    messagingSenderId: '924544352485',
    projectId: 'h3devsss',
    storageBucket: 'h3devsss.appspot.com',
    iosBundleId: 'com.example.h3devs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHa-uzc3YWf7ICAXqBg5DWB_Zs8-euStM',
    appId: '1:924544352485:ios:9ef1220e9eb8eaebfc940c',
    messagingSenderId: '924544352485',
    projectId: 'h3devsss',
    storageBucket: 'h3devsss.appspot.com',
    iosBundleId: 'com.example.h3devs.RunnerTests',
  );
}
